- name: BlueSand » DBus config
  template: src=dbus.conf.j2 dest={{ path }}/dbus.conf

- name: BlueSand » bluez service » disable
  systemd:
    name=bluetooth.service
    enabled=no
    state=stopped

- name: BlueSand » service » dbus_socket directory
  file: dest={{ path }}/dbus_socket state=directory

- name: BlueSand » service » add
  template: src=bluesand.service.j2 dest=/etc/systemd/system/bluesand.service
  notify: restart BlueSand

- name: BlueSand » service » enable
  systemd:
    name=bluesand.service
    daemon_reload=true
    enabled=true
    state=started

